version: "3.9"

services:
    database:
        container_name: ${RDMS_CONTAINER_NAME}
        image: postgres
        user: "${UID}:${GID}"
        environment:
            POSTGRES_DB: ${RDMS_DB_NAME}
            POSTGRES_PASSWORD: ${RDMS_DB_PASSWORD}
            POSTGRES_USER: ${RDMS_DB_USER}
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${RDMS_DB_NAME}", "-U", "${RDMS_DB_USER}"]
            timeout: 5s
            retries: 5
            start_period: 60s
        ports:
            - "5432:5432"
        volumes:
            - ./database/data:/var/lib/postgresql/data:rw
        

