name: GoLint

on:
  push:
    branches:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
        - name: Extract branch name
          run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: ~1.23

        - name: Check out code
          uses: actions/checkout@v3            

        - name: Download dependencies
          run: go mod download          

        - name: Build
          run: |
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o notes_webserver ./cmd/main.go

        - name: Archive files
          run: |
            mkdir -p dist
            cp notes_webserver dist/
            cp -r templates dist/
            cp -r static dist/
            cp .env.example dist/
            tar -czvf dist/notes_webserver.tar.gz -C dist .            

        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: notes_webserver
            path: dist/notes_webserver.tar.gz