name: Builder

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Extract branch name
          run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: ~1.23

        - name: Check out code
          uses: actions/checkout@v4

        - name: Download dependencies
          run: go mod download          

        - name: Build
          run: |
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o notes_webserver ./cmd/main.go

        - name: Archive files
          run: |
            mkdir -p server
            mkdir -p dist
            cp notes_webserver server/
            cp -r templates server/
            cp -r static server/
            cp .env.example server/
            tar -czvf dist/notes_webserver.tar.gz server           

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: notes_webserver
            path: dist/notes_webserver.tar.gz