name: Tests

on:
  push:
    branches:
      - '*'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ~1.23

      - name: Check out code
        uses: actions/checkout@v4

      - name: Unit tests
        run: go test -v -count=100 -race -timeout=1m ./...
        working-directory: .